# Generated by Django 5.2.7 on 2025-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0005_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
