# Generated by Django 5.2.7 on 2025-11-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Срібні Підкови”'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gems',
            field=models.IntegerField(default=0, verbose_name='Срібні Крила'),
        ),
    ]
