# Generated by Django 5.2.7 on 2025-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0009_alter_profile_coins_alter_profile_gems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gems',
            new_name='silver_wings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coins',
        ),
        migrations.AddField(
            model_name='profile',
            name='horseshoes',
            field=models.IntegerField(default=0, verbose_name='Срібні Підкови'),
        ),
    ]
