# Generated by Django 5.2.7 on 2025-11-08 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0012_notification_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='silver_wings',
            field=models.IntegerField(default=0, verbose_name="Срібні Пір'я"),
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Жеребець'), ('F', 'Кобила')], max_length=1)),
                ('coat_color', models.CharField(max_length=50)),
                ('speed', models.IntegerField(default=50)),
                ('endurance', models.IntegerField(default=50)),
                ('strength', models.IntegerField(default=50)),
                ('health', models.IntegerField(default=100)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('market', 'На ринку'), ('user', 'У користувача')], default='market', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
