# Generated by Django 5.2.8 on 2025-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0013_alter_profile_silver_wings_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='horses/'),
        ),
    ]
