# Generated by Django 5.2.8 on 2025-11-17 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0015_equestriancomplex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equestriancomplex',
            name='name',
            field=models.CharField(default='Мій комплекс', max_length=50),
        ),
        migrations.CreateModel(
            name='ComplexRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='userspace.equestriancomplex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('complex', 'user')},
            },
        ),
    ]
