# Generated by Django 5.2.7 on 2026-01-09 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0016_equestriancomplex_name_complexrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення профілю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_new_user',
            field=models.BooleanField(default=True, verbose_name='Новий користувач'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='Текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='horseshoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Срібні Підкови'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='silver_wings',
            field=models.PositiveIntegerField(default=0, verbose_name="Срібні Пір'я"),
        ),
    ]
