# Generated by Django 5.2.7 on 2026-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0017_profile_created_at_profile_is_new_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Перемоги'),
        ),
    ]
