# Generated by Django 6.0.1 on 2026-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0019_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='energy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='horse',
            name='mood',
            field=models.IntegerField(default=100),
        ),
    ]
