# Generated by Django 6.0.2 on 2026-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0020_horse_energy_horse_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='horse_type',
            field=models.CharField(choices=[('riding', 'Верховий кінь'), ('pony', 'Поні'), ('unicorn', 'Єдиноріг'), ('pegasus', 'Пегас')], default='riding', max_length=20, verbose_name='Тип коня'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='status',
            field=models.CharField(choices=[('market', 'На ринку'), ('user', 'У користувача'), ('shelter', 'У притулку')], default='market', max_length=10),
        ),
    ]
