# Generated by Django 6.0.2 on 2026-02-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0021_horse_horse_type_alter_horse_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorsePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='userspace.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Погладжування коня',
                'verbose_name_plural': 'Погладжування коней',
                'unique_together': {('user', 'horse')},
            },
        ),
    ]
