# Generated by Django 6.0.2 on 2026-03-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0022_horsepet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horsepet',
            unique_together=set(),
        ),
    ]
