# Generated by Django 6.0.2 on 2026-03-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0023_alter_horsepet_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved_horseshoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарезервовано на аукціоні'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='status',
            field=models.CharField(choices=[('market', 'На ринку'), ('user', 'У користувача'), ('shelter', 'У притулку'), ('auction', 'На аукціоні')], default='market', max_length=10),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('starting_price', models.PositiveIntegerField()),
                ('current_bid', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('current_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_bidding', to=settings.AUTH_USER_MODEL)),
                ('horse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='userspace.horse')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_selling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
