# Generated by Django 6.0.2 on 2026-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0024_profile_reserved_horseshoes_alter_horse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('horseshoes', 'Срібні Підкови'), ('silver_wings', "Срібні Пір'я")], default='horseshoes', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='reserved_silver_wings',
            field=models.PositiveIntegerField(default=0, verbose_name="Зарезервовано Пір'я"),
        ),
    ]
