# Generated by Django 6.0.2 on 2026-03-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0026_convert_age_to_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='last_sleep',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останній сон'),
        ),
    ]
