# Generated by Django 6.0.2 on 2026-03-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0027_horse_for_sale_horse_last_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='Вагітна'),
        ),
        migrations.AddField(
            model_name='horse',
            name='pregnancy_due_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вік пологів (міс.)'),
        ),
        migrations.AddField(
            model_name='horse',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='userspace.horse', verbose_name='Батько'),
        ),
    ]
