# Generated by Django 6.0.2 on 2026-03-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0028_horse_for_sale_horse_is_pregnant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='name_customized',
            field=models.BooleanField(default=False, verbose_name="Ім'я змінено"),
        ),
    ]
