# Generated by Django 6.0.2 on 2026-03-12 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0029_horse_for_sale_horse_name_customized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='original_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_horses', to=settings.AUTH_USER_MODEL, verbose_name='Первинний власник'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horses', to=settings.AUTH_USER_MODEL),
        ),
    ]
