# Generated by Django 6.0.2 on 2026-03-12 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0030_horse_for_sale_horse_original_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('horseshoes', 'Підкови'), ('silver_wings', "Срібні пір'їни")], default='horseshoes', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_offers', to='userspace.horse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
