# Generated by Django 6.0.2 on 2026-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0031_horse_for_sale_breedingoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingoffer',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість використань'),
        ),
        migrations.AddField(
            model_name='breedingoffer',
            name='remaining_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Залишилось використань'),
        ),
    ]
