# Generated by Django 5.2.7 on 2026-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0032_breedingoffer_max_uses_breedingoffer_remaining_uses_and_more'),
    ]

    operations = [
    ]
