# Generated by Django 5.2.7 on 2026-03-16 11:37

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0033_horse_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='strength',
            field=models.IntegerField(default=50),
        ),
    ]