# Generated by Django 6.0.3 on 2026-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0034_add_strength_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='gallop',
            field=models.FloatField(default=0.0, verbose_name='Галоп'),
        ),
        migrations.AddField(
            model_name='horse',
            name='jumping',
            field=models.FloatField(default=0.0, verbose_name='Стрибки'),
        ),
        migrations.AddField(
            model_name='horse',
            name='trot',
            field=models.FloatField(default=0.0, verbose_name='Рись'),
        ),
    ]
