# Generated by Django 6.0.3 on 2026-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0036_populate_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='endurance',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='horse',
            name='speed',
            field=models.FloatField(default=50.0),
        ),
    ]
