# Generated by Django 6.0.3 on 2026-03-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0037_horse_dressage_horse_for_sale_alter_horse_endurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_dam', to='userspace.horse', verbose_name='Мати'),
        ),
    ]
