# Generated by Django 6.0.3 on 2026-03-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0038_horse_dam_horse_dressage_horse_for_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('type', models.CharField(choices=[('food', 'Їжа'), ('building', 'Будівельний ресурс')], max_length=20, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='userspace.equestriancomplex')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userspace.resource')),
            ],
            options={
                'unique_together': {('complex', 'resource')},
            },
        ),
    ]
