# Generated by Django 6.0.3 on 2026-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0040_add_initial_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Ціна (Срібні Підкови)'),
        ),
    ]
