# Generated by Django 6.0.3 on 2026-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0042_set_resource_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='pending_health_loss',
            field=models.IntegerField(default=0, verbose_name="Відкладена втрата здоров'я"),
        ),
    ]
