# Generated by Django 6.0.3 on 2026-04-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0043_horse_dressage_horse_for_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='last_sleep_processed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата застосування ефектів сну'),
        ),
    ]
