# Generated by Django 6.0.3 on 2026-04-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0044_horse_dressage_horse_energy_at_sleep_horse_for_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('competition_type', models.CharField(choices=[('barrel_racing', 'Перегони навколо бочок'), ('cutting', 'Каттинг'), ('trail', 'Трейл'), ('reining', 'Рейнінг'), ('grand_prix', 'Гран-Прі'), ('western_pleasure', 'Вестерн плежер')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('primary_skill', models.CharField(choices=[('speed', 'Швидкість'), ('endurance', 'Витривалість'), ('dressage', 'Виїздка'), ('gallop', 'Галоп'), ('trot', 'Рись'), ('jumping', 'Стрибки')], max_length=20)),
                ('secondary_skill', models.CharField(blank=True, choices=[('speed', 'Швидкість'), ('endurance', 'Витривалість'), ('dressage', 'Виїздка'), ('gallop', 'Галоп'), ('trot', 'Рись'), ('jumping', 'Стрибки')], max_length=20, null=True)),
                ('energy_cost', models.PositiveSmallIntegerField(default=20)),
                ('max_participants', models.PositiveSmallIntegerField(default=8)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Змагання',
                'verbose_name_plural': 'Змагання',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Зареєстровано'), ('finished', 'Завершено'), ('cancelled', 'Скасовано')], default='registered', max_length=15)),
                ('result_place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reward_horseshoes', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='userspace.competition')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_registrations', to='userspace.horse')),
            ],
            options={
                'verbose_name': 'Реєстрація на змагання',
                'verbose_name_plural': 'Реєстрації на змагання',
                'unique_together': {('horse', 'competition')},
            },
        ),
    ]
