# Generated by Django 6.0.3 on 2026-04-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0045_competition_horse_dressage_horse_energy_at_sleep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='currency',
            field=models.CharField(choices=[('horseshoes', 'Срібні підкови'), ('silver_wings', "Срібні пір'їни")], default='horseshoes', max_length=20, verbose_name='Валюта'),
        ),
    ]
